nelmio_cors:
  defaults:
    allow_origin: ["*"] # Замените на ['http://localhost:5173'] для ограничения по источникам
    allow_methods: ["GET", "POST", "OPTIONS", "PUT", "DELETE"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: []
    max_age: 3600
    hosts: []
  paths:
    "^/api/": # Путь, к которому применяются настройки CORS
      allow_origin: ["*"] # Укажите разрешенные источники
      allow_headers: ["Content-Type", "Authorization"]
      allow_methods: ["GET", "POST", "OPTIONS", "PUT", "DELETE"]
